# Generated by Django 5.2.17 on 2026-08-11 22:49

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='dropoff_latitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='ride',
            name='dropoff_longitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickup_latitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickup_longitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
        migrations.AddConstraint(
            model_name='ride',
            constraint=models.CheckConstraint(condition=models.Q(('pickup_latitude__gte', -90.0), ('pickup_latitude__lte', 90.0), ('pickup_longitude__gte', -180.0), ('pickup_longitude__lte', 180.0)), name='ride_pickup_coordinates_within_earth'),
        ),
        migrations.AddConstraint(
            model_name='ride',
            constraint=models.CheckConstraint(condition=models.Q(('dropoff_latitude__gte', -90.0), ('dropoff_latitude__lte', 90.0), ('dropoff_longitude__gte', -180.0), ('dropoff_longitude__lte', 180.0)), name='ride_dropoff_coordinates_within_earth'),
        ),
    ]
